### ISSUE TITLE
Package update jms/serializer

### ISSUE THREAD

**Issue by davidbrainspin** [billbeeio/custom-shop-php-sdk#5]
Moin Julian @devtronic,
besteht die Möglichkeit das Package **jms/serializer** von Version **1.14.1** auf **^3.3** zu updaten?

https://github.com/schmittjoh/serializer
Aktueller Release 3.14.0

**Comment by devtronic** [comment]
Moin,

ich habe die Version aktualisiert. Kannst du mit diesem Branch mal testen, ob alles funktioniert? Die Unit Tests laufen auf jeden Fall durch.
https://github.com/billbeeio/custom-shop-php-sdk/pull/6

Wenn alles passt, Update ich das Composer Package.

**Comment by davidbrainspin** [comment]
Danke Julian für die schnelle Antwort und das Update!

Soweit sieht alles gut aus. Ich teste die Anwendung in den kommenden Tagen weiter und gebe erneut Bescheid!

**Comment by davidbrainspin** [comment]
@devtronic Im weiteren Testing ist nichts aufgefallen. Passt von meiner Seite aus.
